[RunSvc]
JobName = "fsf_training"
BeamType = "IAEA"
PhspInputFileName = "/mnt/data/PHSP/TB_20X20_Merged"
# PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH Dell-XPS location
# PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_3x3s2-f0" # AGH LHCBD2 location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location 

PhspEvtVrtxMultiplicityTreshold = 20
PrintProgressFrequency = 0.05
Physics = "LowE_Penelope" #  "LowE_Livermore" "LowE_Penelope" "emstandard_opt3"

GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = false
RunAnalysis = true

WriteFieldMaskToCsv = true

StoreTracks= false
StorePositions= false
StoreEnergies = false
StorePrimaries = false
StoreRunInfo= false
MinimalMode= true

[GeoSvc]
BuildLinac = true
BuildPatient = true
MlcModel="Simplified"
[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 64.0
EnviromentSizeY = 64.0
EnviromentSizeZ = 64.0
EnviromentMedium = "Usr_G4AIR20C"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,1.0,0.0] # In mm
Voxelization = [4,4,2] # Number of cels in every direction

[D3DDetector_Cell]
Medium = "RMPS470"
Voxelization = [10,10,10]
TracksAnalysis = false
CellVoxelisedScorer = true

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
nParticles = 1000 # Per Control Point
BeamRotation = 0
PlanInputFile = [
        # "plan/custom/custom/cp0_1x2_0_0.dat",
        # "plan/custom/custom/cp0_1x2_0_1.dat",
        # "plan/custom/custom/cp0_1x2_0_3.dat",
        # "plan/custom/custom/cp0_1x2_1_3.dat",
        # "plan/custom/custom/cp0_1x2_2_0.dat",
        # "plan/custom/custom/cp0_1x2_2_3.dat",
        # "plan/custom/custom/cp0_1x1_3_0.dat",
        # "plan/custom/custom/cp0_1x1_3_3.dat",
        "plan/custom/custom/cp0_1x1_3_3.dat"
        # "plan/custom/srunet_test/fsf_inpact_cp0_1x1_2_1.dat",
        # "plan/custom/srunet_test/fsf_inpact_cp0_1x1_1_2.dat",
]